spring:
  application:
    name: eureka-client-article-service
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    #采用IP注册
    prefer-ip-address: true
    #定义实例ID
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-adress}:${server.port}